### ISSUE TITLE
强烈推荐建议适配chrome书签json结构，方便一键导出生成

### ISSUE THREAD

**Issue by fulige18** [arleycn/arleybookmarks#1]
如题，强烈建议大佬能否适配一下chrome书签的结构，因为日常都是用chrome收藏，更改。我觉得效率简直不要太高，门槛又低。
现有我发现的有2款书签导出插件：
一个是Export History/Bookmarks to JSON/CSV*/XLS*[https://chrome.google.com/webstore/detail/export-historybookmarks-t/dcoegfodcnjofhjfbhegcgjgapeichlf](https://github.com/liuyike98/233-nav-page/issues/url)
一个是json-bookmarks[https://github.com/1nfiniteloop/json-bookmarks](https://github.com/liuyike98/233-nav-page/issues/url)
。

**Comment by arleycn** [comment]
> 如题，强烈建议大佬能否适配一下chrome书签的结构，因为日常都是用chrome收藏，更改。我觉得效率简直不要太高，门槛又低。
> 现有我发现的有2款书签导出插件：
> 一个是Export History/Bookmarks to JSON/CSV*/XLS*[https://chrome.google.com/webstore/detail/export-historybookmarks-t/dcoegfodcnjofhjfbhegcgjgapeichlf](https://github.com/liuyike98/233-nav-page/issues/url)
> 一个是json-bookmarks[https://github.com/1nfiniteloop/json-bookmarks](https://github.com/liuyike98/233-nav-page/issues/url)
> 。


 大佬谈不上，就是美化了[WebStackPage](https://github.com/WebStackPage/WebStackPage.github.io)的项目。
其实我也想过把站点分出来，利用js或其他方式添加到`index.html`中，这样也减小了它的体量，对浏览速度会有一定的影响，等有时间学习下;
后续的计划:
>可能会有(自适应)暗黑模式
>会改变书签的添加方式
>有能力的话会优化css内无用代码

**Comment by arleycn** [comment]
> 如题，强烈建议大佬能否适配一下chrome书签的结构，因为日常都是用chrome收藏，更改。我觉得效率简直不要太高，门槛又低。 现有我发现的有2款书签导出插件： 一个是Export History/Bookmarks to JSON/CSV*/XLS*[https://chrome.google.com/webstore/detail/export-historybookmarks-t/dcoegfodcnjofhjfbhegcgjgapeichlf](https://github.com/liuyike98/233-nav-page/issues/url) 一个是json-bookmarks[https://github.com/1nfiniteloop/json-bookmarks](https://github.com/liuyike98/233-nav-page/issues/url) 。

我又看了下原作者的github项目，发现一个方便导入浏览器书签的导航网站项目，具体项目地址请点击[webstack-jekyll](https://github.com/hanxi/webstack-jekyll)，测试了下只支持书签一级目录，二级以下不识别或者未开发。
